name: 'Setup Node.js with Cache'
description: 'Setup Node.js and restore yarn cache (requires checkout first)'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

runs:
  using: 'composite'
  steps:
    - name: Setup node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore dependencies from cache
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
      with:
        path: |
          node_modules
          apps/*/node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
